### ISSUE TITLE
[metascraper-media-provider] YouTube randomly fails under heavy load

### ISSUE THREAD

**Issue by Hereward** [microlinkhq/metascraper#202] opened 2019-08-07 12:54 UTC
- I'm using the last version.
- My node version is the same as declared as `package.json`.

Youtube scrape returns null for most fields.

The package works, there are no errors but author, date, description and logo are all null. The title is always "Youtube".

The only correctly returned is the image (see attached image)
![youtube_scrape](https://user-images.githubusercontent.com/1784096/62624160-ab0e3980-b94c-11e9-9e75-617747cdd94a.JPG)

NOTE: I have added the metascraper-youtube package.

### Steps to reproduce

```js
function meta(id, targetUrl, body, DataSource) {
  const metascraper = require("metascraper")([
    require("metascraper-author")(),
    require("metascraper-date")(),
    require("metascraper-description")(),
    require("metascraper-image")(),
    require("metascraper-logo")(),
    require("metascraper-clearbit")(),
    require("metascraper-publisher")(),
    require("metascraper-title")(),
    require("metascraper-url")(),
    require("metascraper-youtube")()
  ]);

  (async (request, response, next) => {
    try {
      const metadata = await metascraper({ html: body, url: targetUrl });
      const imageURL = metadata.image ? sanitizeUrl(metadata.image) : "";

      const linkMetaData: any = {
        title: formatTitleField(metadata.title),
        description: processSummaryField(metadata.description, 200),
        image: imageURL,
        url: formatInputFields(metadata.url),
        publisher: formatInputFields(metadata.publisher)
      };

      DataSource.update(id, {
        $set: { linkMetaData: linkMetaData }
      });

      if (imageURL) {
        const dimensions = getImageDimensionsFromUrlRequest(imageURL);
        if (dimensions) {
          linkMetaData.imageWidth = dimensions.width;
          linkMetaData.imageHeight = dimensions.height;
        }
        DataSource.update(id, {
          $set: { linkMetaData: linkMetaData }
        });
      }
    } catch (error) {
      log.error(error);
    }
  })();
}
```

### Expected behaviour

Title and Description fields should have data.

### Actual behaviour

These fields are null.

**Comment by Kikobeats** [comment] 2019-08-07 18:08
I need to investigate a bit; trying to retrieve YouTube info from Microlink API (metascraper as service) it works as expected:

https://api.microlink.io/?url=https://www.youtube.com/watch?v=wBSBVjZFsOQ&video

**Comment by Hereward** [comment] 2019-08-08 03:13
Am I missing a rule bundle? I'm not clear as to the function of some of the rule bundles (eg uol) as there is no description given.

**Comment by Hereward** [comment] 2019-08-08 03:14
I have now added "metascraper-video" - but it too yields no data.

**Comment by Kikobeats** [comment] 2019-08-09 07:46
I can't reproduce this behavior; I've run the test suite over metascraper (especially tests related to youtube) and they work fine.

Can you try

1. fork the repo (https://github.com/microlinkhq/metascraper)
2. npm install & npm test

**Comment by dompenn2010** [comment] 2019-08-15 21:58
@Kikobeats we're seeing similar behavior, but never locally, only in a deployed dev environment. 

It initially works for a number of requests then it's as if YouTube stops sending metadata. 

Is there anything you're aware of that might cause YT to flag a Heroku instance or anything like that?

**Comment by Kikobeats** [comment] 2019-08-16 06:35
@dompenn2010 that sounds a bit familiar to me and I saw this behavior after running some Travis CI builds in a very consecutive way.

Need to investigate a bit deeply there to figure out what's happening, but probably YouTube server is adding the request IP in a blacklist for preventing abuse.

In that case, we can implement there a retry strategy; that's a thing we are already doing for [Twitter video](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-media-provider/src/get-media/provider/twitter.js#L23)

**Comment by Hereward** [comment] 2019-08-16 11:12
In my tests the function was failing both in local dev and in production. I have switched to using the Google API directly which works as expected in all environments.

**Comment by dompenn2010** [comment] 2019-08-16 22:24
> In that case, we can implement there a retry strategy; that's a thing we are already doing for [Twitter video](https://github.com/microlinkhq/metascraper/blob/master/packages/metascraper-media-provider/src/get-media/provider/twitter.js#L23)

Ah!

Interesting. Thanks for the quick reply!

**Comment by Kikobeats** [comment] 2019-08-17 11:30
@dompenn2010 we can implement the same thing here, or use YouTube API at `metascraper-youtube` as @Hereward suggest (or create a new one package, like `metascraper-youtube-api`)

@Hereward can you share your code? maybe creating a PR? 🙂

**Comment by dompenn2010** [comment] 2019-08-17 11:52
@Kikobeats not to take away from the fact that this may be a legitimate bug, but it's working reliably for us again. 

I'll keep an eye on this issue though, and if anything funny happens we'll investigate if there hasn't been a resolution yet.

**Comment by Kikobeats** [comment] 2019-08-30 21:00
<img width="1280" alt="Screenshot 2019-08-30 at 22 55 40" src="https://user-images.githubusercontent.com/2096101/64050897-b59da680-cb79-11e9-8c5a-ef7bc0beabc8.png">

I tried to reproduce the error on my local without success.

Steps for doing the same:

1. edit `bench/constants.js` with youtube video URLs.
2. run `DEBUG=* node bench/provider/generic.js` as you can.
3. wait until `hasMedia? false` appear on the terminal.

can you try to reproduce it under a production environment?

**Comment by iamandyk** [comment] 2019-09-11 19:45
I too, am experiencing this error where certain fields are null and title is always `YouTube`.

**Comment by Kikobeats** [comment] 2019-09-11 23:15
I'm getting some production registries over this, so I hope to improve this soon 🙂

**Comment by harisdz** [comment] 2019-09-16 12:28
This is happening to me as well, 100% of the time and in dev, stg and production

**Comment by iamandyk** [comment] 2019-10-02 13:25
What if we use the `oembed` url? Like this one [https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=B3IRK1kVvWI&format=json](https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=B3IRK1kVvWI&format=json)

**Comment by Kikobeats** [comment] 2019-11-18 14:36
I'm going to close this because there is nothing we can do there since YouTube is clearly banning consecutive requests under a production scenario.

I want to suggest two workaround there:

1) Use a proxy for doing consecutive request for getting the HTML.
2) Use [metascraper-iframe](https://github.com/microlinkhq/metascraper/tree/master/packages/metascraper-iframe), it's a new package with oembed support (.cc @iamandyk)

**Closed by Kikobeats** 2019-11-18 14:36 UTC
Labels: help wanted
