### ISSUE TITLE
Running metascraper in the browser?

### ISSUE THREAD

**Issue by shash7** [microlinkhq/metascraper#310] opened 2020-09-29 14:04 UTC
### Prerequisites
NA
### Subject of the issue
How to run metascraper in client-side javascript

### Steps to reproduce
NA

### Expected behaviour
NA

### Actual behaviour
NA

Is there a way to run metascraper inside a browser?

**Comment by Kikobeats** [comment] 2020-09-29 16:27
duplicate of https://github.com/microlinkhq/metascraper/issues/61

**Closed by Kikobeats** 2020-09-29 16:27 UTC
Labels: question

**Comment by Eunoia** [comment] 2020-10-21 04:37
It was really important for me to run metascraper on the client, because I needed speed, and to add a couple extra custom settings for my use case. Using browserify with tinyify (tree shaking, minimization, etc) to load metascraper and all the dependancies on the client comes to about 824K of javascript, which is pretty big. For my use case as part of a bookmarklet, it's only loaded once, and from cache thereafter.

The repo where I did this is here: <https://github.com/Eunoia/roamImporter>
