### ISSUE TITLE
TypeError: memoizeOne is not a function

### ISSUE THREAD

**Issue by zhaoxuyll** [microlinkhq/metascraper#261] opened 2020-02-01 08:50 UTC
### Prerequisites

- [x] I'm using the last version.
- [x] My node version is the same as declared as `package.json`.

### Subject of the issue

Error when packaging using Webpack.
```
e:\weizhi\server\dist\webpack:\node_modules\@metascraper\helpers\index.js:234
const jsonld = memoizeOne((url, $) => {
^
TypeError: memoizeOne is not a function
    at Object../node_modules/@metascraper/helpers/index.js (e:\weizhi\server\dist\webpack:\node_modules\@metascraper\helpers\index.js:234:1)
    at __webpack_require__ (e:\weizhi\server\dist\webpack:\webpack\bootstrap:25:1)
    at Object../node_modules/metascraper/src/index.js (e:\weizhi\server\dist\webpack:\node_modules\metascraper\src\index.js:3:19)
    at __webpack_require__ (e:\weizhi\server\dist\webpack:\webpack\bootstrap:25:1)
```

### Steps to reproduce

> **Note**: You can reproduce the code using [interactive Node.js shell by Runkit](https://npm.runkit.com/metascraper).

Packaging projects with Webpack and starting program.

### Expected behaviour

No error.

### Actual behaviour

When "module" (ESM) is used in the "package.json" file of "memoize-one", Webpack will parse it first, but Nodejs "require" no support "exports default", 
I can only do this require('memoize-one').default to get rid of errors.

**Comment by Kikobeats** [comment] 2020-02-01 09:47
why are you using webpack with metascraper?

**Comment by Kikobeats** [comment] 2020-02-01 09:56
Duplicate of https://github.com/microlinkhq/metascraper/issues/255

A PR improving this and make it compatible with webpack is very welcome, otherwise, I can't spend time on this since the library is oriented to be used on the server side.

**Closed by Kikobeats** 2020-02-01 09:56 UTC

**Comment by zhaoxuyll** [comment] 2020-02-03 01:47
@Kikobeats I believe webpack is also used in server packaging.

**Comment by zhaoxuyll** [comment] 2020-02-04 01:25
@Kikobeats I open issues to memoize-one, this is reply https://github.com/alexreardon/memoize-one/issues/80
