### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by NullVoxPopuli** [microlinkhq/metascraper#27] opened 2017-04-29 13:31 UTC
when I try to get tags from github, and many other sites, I get a similar error to the one below:

```
XMLHttpRequest cannot load https://github.com/ianstormtaylor/metascraper/issues/new. 
Redirect from 'https://github.com/ianstormtaylor/metascraper/issues/new' to 
  'https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fianstormtaylor%2Fmetascraper%2Fissues%2Fnew' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:4201' is therefore not allowed access.
```

Is there anyway to ignore this? or a method of retrieving the page like a browser would?

**Comment by blakeembrey** [comment] 2017-04-29 22:04
This would probably just need a `process.browser` switch to create an XHR transport with credentials enabled in the browser (not tested, but I'm sure it'd just be caused by cookies not being attached). This would deviate from how node requests it but that's how it'd be fixed if you wanted it fixed.

**Comment by NullVoxPopuli** [comment] 2017-04-29 22:12
yeah -- I don't know how else to get the meta from other websites otherwise. :-\

**Comment by blakeembrey** [comment] 2017-04-29 22:57
You can start with https://github.com/ianstormtaylor/metascraper/blob/27340b24e463397ad18aedb15f43546c0626b07e/lib/index.js#L26-L37 and replace the request mechanism. E.g.

```ts
function scrape (url, rules) {
  return popsicle.get({
    url: url,
    transport: popsicle.createTransport({ withCredentials: true })
  }).then(res => scrapeMetadata(res.body, url, rules))
}

**Comment by leeeejuy** [comment] 2017-05-28 04:15
fg

**Comment by Kikobeats** [comment] 2017-12-10 18:26
Hello,

I'm going to close this because new [2.0.0](https://github.com/microlinkhq/metascraper/issues/40) iteration doesn't handle HTTP layer anymore!

**Closed by Kikobeats** 2017-12-10 18:26 UTC
