### ISSUE TITLE
Using metascraper library in React

### ISSUE THREAD

**Issue by paulina-grunwald** [microlinkhq/metascraper#248] opened 2019-12-24 08:03 UTC
Hi,
I was trying to import this library in my react app with no success. Would it even work with React? How can I import it?

**Comment by Kikobeats** [comment] 2019-12-24 09:16
Hello! 

Probably you can use it at frontend level (like React), although the library has been mainly designed to be used from backend side;

That doesn't mean it can't be done, just need to figure out the best way to accommodate it in a frontend stuff

Duplicate of https://github.com/microlinkhq/metascraper/issues/95

**Closed by Kikobeats** 2019-12-24 09:16 UTC
Labels: question
